apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api
  namespace: bookstore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      bookstore: web
  template:
    metadata:
      labels:
        bookstore: web
    spec:
      containers:
      - name: bookstore-site
        image: bookstore
---
apiVersion: v1
kind: Service
metadata:
  name: bookstpre-entrypoint
  namespace: bookstore-app
spec:
  type: NodePort
  selector:
    bookstore: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
