apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.8.1
      args:
        - "--dockerfile=./Dockerfile"
        - "--context=git://github.com/jobm/flask-restless-api.git#refs/heads/master"
        - "--destination=jobm/bookstore-api:v0.0.1"
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-token
              key: GIT_TOKEN
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: docker-regcred
        items:
          - key: .dockerconfigjson
            path: config.json
