version: '3.6'

services:
  web:
    env_file:
      - .flaskenv
    build: .
    command: gunicorn -b 0.0.0.0:5000 api.wsgi:app
    depends_on:
      - db
    environment:
      STAGE: deveopment
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./api:/code/api
      - ./db/:/db/
    restart: always

  db:
    env_file:
      - ./.envs/.psqlenv
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  keycloak-db:
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=123456
    image: postgres:latest
    networks:
      - default
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  keycloak-server:
    env_file:
      - ./.envs/.keycloakenv
    image: jboss/keycloak
    networks:
      - default
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
